language: python
python:
  - "2.7"
cache: pip
before_install:
  - sudo apt-get install python-dev libsdl-mixer1.2 libusb-1.0 libsdl1.2-dev mercurial python-pyaudio
install:
  - python setup.py install
script:
  - python setup.py test